export const SINGIN = "SINGIN"
export const lOGOUT = "lOGOUT"

export const LLENARNEWTRAVELS = "LLENARNEWTRAVELS"
export const ADDITEMTONEWTRAVEL = "ADDITEMTONEWTRAVEL"
export const EDITITEMTRAVEL = "EDITITEMTRAVEL"
export const DELETEITEMTRAVEL = "DELETEITEMTRAVEL"

export const ASIGNARPOSITION = "ASIGNARPOSITION"

export const CONECT = "CONECT"
export const DISCONET = "DISCONET"

export const LLENARWALLETS = "LLENARWALLETS"
export const CLEARWALLETS = "CLEARWALLETS"

export const UPDATEAVATAR = "UPDATEAVATAR"